version: 2
updates:
  # Maintain dependencies for Pulpcore
  - package-ecosystem: "pip"
    directory: "/automation"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[dependabot]"
    # Add labels for dependabot bumps
    labels:
      - "dependabot"
