version: 2
updates:
  # Maintain dependencies for Pulpcore
  - package-ecosystem: "pip"
    open-pull-requests-limit: 10
    directory: "/automation"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[dependabot]"
    # Add labels for dependabot bumps
    groups:
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
       pulp-cli-deps:
          # Define patterns to include dependencies in the group (based on
          # dependency name)
          applies-to: version-updates # Applies the group rule to version updates
          patterns:
            - "pulp-cli"
            - "pulp-glue"
       pulp-cli-deb-deps:
          applies-to: version-updates
          patterns:
            - "pulp-cli-deb"
            - "pulp-glue-deb"
    labels:
      - "dependabot"
    ignore:
      - dependency-name: "pulpcore*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-rpm*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-ostree"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-python"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-deb"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-container"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-ansible"
        update-types: ["version-update:semver-minor"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[dependabot]"

